services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
image: earthly/earthly:v0.8.5

before_script:
    - earthly bootstrap
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 

earthly:
  stage: build
  script:
    - earthly --org TaroBill --sat my-satellite --ci --push -P +ci
  tags:
    - Run in Docker