version: '1'

services:
  nats-jetstream:
    image: "nats:2.10.14-alpine3.19"
    container_name: "nats-jetstream"
    ports:
      - "32803:32803"
    command:
      - /bin/sh
      - -c
      - |
        nats-server --port 32803 --js --http_port 8222 --store_dir /data
    networks:
      - nats

  gravity-dispatcher:
    image: "e85ccfdca268"
    # restart: always
    container_name: "gravity-dispatcher"
    environment:
      - GRAVITY_DISPATCHER_GRAVITY_HOST=nats-jetstream
      - GRAVITY_DISPATCHER_GRAVITY_PORT=32803
    depends_on:
      - "nats-jetstream"
    entrypoint: /bin/sh
    command:
      - -c
      - |
        until wget -qO- http://$${GRAVITY_DISPATCHER_GRAVITY_HOST}:8222/healthz | grep -qi "ok"; do
          echo "Waiting for $${GRAVITY_DISPATCHER_GRAVITY_HOST}:8222 to be ready"
          sleep 1;
        done
        /gravity-dispatcher
    networks:
      - nats
  atomic:
    image: "ghcr.io/brobridgeorg/atomic/atomic:v0.0.5-20231012-ubi"
    # restart: always
    container_name: "atomic"
    volumes:
      - "./assets/atomic:/data/atomic"
    depends_on:
      - "nats-jetstream"
      - "gravity-dispatcher"
    user: "1001:1000"
    ports:
      - 1880:1880
    entrypoint: /bin/sh
    command:
      - -c
      - |
        npm start --cache /data/atomic/.npm -- --userDir /data/atomic /data/atomic/flows.json
    networks:
      - nats
networks:
  nats: {}
