name: Earthly Test
run-name: ${{ github.actor }} is testing 
on:
  pull_request:
    branches:
      - master 
jobs:
   checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
  earthly:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - run:  earthly bootstrap
      - name: Check for Earthfile file
        run: (ls Earthfile && echo Found Earthfile) || (echo No Earthfile)
        id: check

      - name: Run Earthly and capture output
        id: earthly
        run: |
          output=$(earthly --ci --push -P +ci 2>&1)
          echo "$output"
          coverage=$(echo "$output" | grep "total:" | sed 's/.*)\s*//')
          echo "coverage=$coverage" >> $GITHUB_OUTPUT

      - name: Create coverage badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: coverage
          LABEL: 'Coverage'
          STATUS: ${{ steps.earthly.outputs.coverage }}
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}